---
blank_issues_enabled: false
contact_links:
  - name: Final Project Python Albert Parlys PYT4 DTS 2022 Community Support
    url: https://github.com/albertparlys/final-project-python-pyt-4-dts-2022/discussions
    about: Please ask and answer questions here.
